#spring:
#  activemq:
#    broker-url: tcp://localhost:61616


camel:
  component:
    servlet:
      mapping:
#        context-path: /*
        context-path: /test/*
        enabled: true



server:
  port: 8080 #Specify port for camel servlet
#  max-http-header-size: 32768