#spring:
#  activemq:
#    broker-url: tcp://localhost:61616



camel:
  component:
    aws-ec2:
      access-key: ${AWS_ACESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
      region: eu-west-1
  servlet:
    mapping:
      context-path: /apis/*
      enabled: true

jasypt:
  encryptor:
    bean: jasyptStringEncryptor


server:
  port: 8080 #Specify port for camel servlet
#  max-http-header-size: 32768